import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-gradient-to-r from-cyan-500 to-sky-700 ${inter.className}`}
      >
        <Navbar />
        <div className="md:w-8/12 mx-auto border border-cyan-50 p-5">
          {children}
        </div>
      </body>
    </html>
  );
}
